### PR TITLE
Remove minimum adapter overlap setting for 10X samples

### PR DESCRIPTION
**Pull request by alexiswl**

### CODE REVIEW

**Review by victorskl — COMMENTED** [review]
Taking over the branch to update unit test as well as bringing it to latest dev HEAD. FYI

**Review by victorskl — APPROVED** [review]
This is good to go now; will merge in tick soon.

**Comment by victorskl** [comment]
Merging...

**Comment by victorskl** [comment]
Related https://github.com/umccr/cwl-ica/pull/91

**Comment by alexiswl** [comment]
Related failsafe check: https://github.com/umccr/infrastructure/pull/223

**Pull request merged**
