### PR TITLE
Make stringent LabMetadataRule check for workflow run

### PR DESCRIPTION
**Pull request by victorskl**
* This fixes running normal sample to tumor only workflow. It relies on
  LabMetadata annotation more. Validation rule evaluates meta info columns
  in order workflow, type, assay, phenotype. Skip on first violation found.

### CODE REVIEW

**Comment by alexiswl** [comment]
Couple of questions: 

1. Is it possible to have cttso be non-tumor? If not, why do we need 'must_be_tumor' to pass for this workflow?  

2. Likewise with the changes to the wts workflow, is this something we need to consider updating for every new workflow that is added to the portal.  Say we add in workflow_x, would we then need to add for all existing workflows - must_not_workflow_x()?

**Comment by victorskl** [comment]
> 1. Is it possible to have cttso be non-tumor? If not, why do we need 'must_be_tumor' to pass for this workflow?

It is up to the analysis workflow (CWL), actually. We can lift up the rule if that is not applicable. Having said, I put them tumor phenotype check there; purely following workflow name semantic:

https://github.com/umccr/data-portal-apis/blob/0e93d970dcb0fdfedcb135dcf23a2e8ae7f25ced/data_processors/pipeline/domain/workflow.py#L34-L35

So far, we have no history of ctTSO ctDNA sample being normal but tumor only. But there are cases where normal sample submission for WTS.


> 2. Likewise with the changes to the wts workflow, is this something we need to consider updating for every new workflow that is added to the portal.  Say we add in workflow_x, would we then need to add for all existing workflows - must_not_workflow_x()?

If you mean, whether we gotta do LabMetadataRule check into every CWL workflow step module job prep, then yes. They could be similar or, different. Also note that "workflow" rule check here is "workflow" annotation from LabMetadata that set for a Sample/Library. Not our CWL workflow... And it is LabMetadataRule check against should a Library be run.

**Comment by victorskl** [comment]
Ah well, we have ticket! More of this #272

**Review by reisingerf — APPROVED** [review]
LGTM
(better to have too many checks and be too explicit than having to sort out the mess afterwards)

**Comment by victorskl** [comment]
@alexiswl @skanwal Hope this is ok with explanation. This is more on guarding against Lab metadata. I will need to merge this soon to prod. So that I can carry other T/N backlog re-run before next sequencing starts...

**Comment by victorskl** [comment]
Pushing through for now. Happy to continue discuss, if any. We can, of course, alter it back if need be.

**Pull request merged**
