### PR TITLE
implemented labmeta api endpoint

### PR DESCRIPTION
**Pull request by andrei-seleznev**
LabMetadata endpoint similar to LIMSRow

### CODE REVIEW

**Comment by victorskl** [comment]
🙀 pretty quick Andrei, kudos! Is this ready for review or wip still? I guess, endpoint name `/labmeta` sorta stick! 😅 

```
GET /labmeta/
GET /labmeta/<id>
```

**Comment by andrei-seleznev** [comment]
The name really did stick!

We only want a GET endpoint, right, not POST? Its really to review as long as we're just after /labmeta and /labmeta/<id> endpoints - not a lot of code there.

**Comment by victorskl** [comment]
Yep; ReadOnly GET/OPTION/HEAD for now. PR is LGTM from my side. May be let check @reisingerf for any comment. Flo, any opinion for endpoint naming?

**Comment by reisingerf** [comment]
LGTM
As for endpoint naming. `/labmeta` is short, specific and follows the current naming scheme. No objections there.
However, we are planning to "extend" those metadata records with additional annotations (from outside the lab metadata sheet, e.g. sequence run ID/Illumina ID, library valid flag, custodian link(s), Trello link(s), ...). In that sense would it make sense to use a more generic `/metadata` under which we can group those?

**Comment by andrei-seleznev** [comment]
ordering fields in viewsets.py set to '__all__' for labmetadata in this forced-push

**Comment by victorskl** [comment]
> In that sense would it make sense to use a more generic `/metadata` under which we can group those?

Yep, sound good. Agree with `/metadata`. @andrei-seleznev Pls kindly amend, thkz.

**Review by victorskl — APPROVED** [review]

**Comment by victorskl** [comment]
@andrei-seleznev FYI, I will merge this.

**Pull request merged**
