### PR TITLE
Started fixing discovery of holmes endpoints

### PR DESCRIPTION
**Pull request by andrewpatto**

### CODE REVIEW

**Comment by andrewpatto** [comment]
For the next release - fixes the way services are discovered - but also will convert the check step to use some of the new lambdas

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Update Holmes interface for new way of check and extract calls](https://trello.com/c/86jSEnb8/1483-portal-release-ocicat-update-holmes-interface-for-new-way-of-check-and-extract-calls)

**Review by victorskl — APPROVED** [review]
Nice one, Patto..!

**Comment by victorskl** [comment]
Morning @andrewpatto Patto, any more commits for changes, good to merge..?

**Comment by andrewpatto** [comment]
ready to merge.. will do

**Pull request merged**
