### PR TITLE
Updated doc on IAM endpoint role permission requirement

### PR DESCRIPTION
**Pull request by victorskl**

### CODE REVIEW

**Comment by victorskl** [comment]
FYI @alexiswl

**Comment by alexiswl** [comment]
Thanks @victorskl have used it in my code here: https://github.com/umccr/cttso-ica-to-pieriandx/blob/dev/deploy/cttso-ica-to-pieriandx-cdk/lib/cttso-ica-to-pieriandx-redcap-lambda-stack.ts#L106-L124

**Comment by victorskl** [comment]
Awesome! I will add a pointer to code excerpt in doc, next round of update.

_(It works, right, btw? Um, it should... 😁)_

**Comment by alexiswl** [comment]
Yep is working fine for my cdks.

**Comment by victorskl** [comment]
Fab! thanks for update

**Pull request merged**
