### PR TITLE
Fastq list rows are now inside the tso500_sample configuration for cttso

### PR DESCRIPTION
**Pull request by alexiswl**
Sorry I didn't do this PR earlier

### CODE REVIEW

**Comment by victorskl** [comment]
[Portal Release - Ocicat: ctTSO update to 1.2](https://trello.com/c/i7gnq6pt/1509-portal-release-ocicat-cttso-update-to-12)

**Review by victorskl — APPROVED** [review]
👍

**Comment by victorskl** [comment]
@alexiswl ready to merge...

**Comment by alexiswl** [comment]
Are you merging this or am I?

**Comment by victorskl** [comment]
Ok, I will merge it.

**Pull request merged**
