### PR TITLE
Release 2.2.2rc1

### PR DESCRIPTION
**Pull request by victorskl**
Release `2.2.2rc1` for Staging

### CODE REVIEW

**Comment by victorskl** [comment]
Knowing Flo might be away for the day, if any of you can give tick approve then I can merge it to Staging.

Flo; this is rc1. Need Portal changes to test RNAsum-1.0.0 validation run in Staging.

ditto previous Failed run - https://umccr.slack.com/archives/C017F7HHWF6/p1717125185463619

**Comment by victorskl** [comment]
(Also to note)

These commits are already peer reviewed. So, no worries much on changes. It is more of formal/Portal release gating purpose.

**Review by pdiakumis — APPROVED** [review]

**Review by skanwal — APPROVED** [review]

**Comment by victorskl** [comment]
Thanks folks. Merging...

**Comment by victorskl** [comment]
Build passed for Staging - https://umccr.slack.com/archives/C017F7HHWF6/p1717134402315069

**Pull request merged**
