### PR TITLE
Handle differing workflow parameters between wts qc and wgs qc

### PR DESCRIPTION
**Pull request by alexiswl**
## WGS
```
        workflow_input["enable_duplicate_marking"] = True
        workflow_input["enable_rna"] = False
        # Drop rna specific parameters
        _ = workflow_input.pop("enable_rna_quantification")
        _ = workflow_input.pop("enable_rrna_filter")
        _ = workflow_input.pop("annotation_file")

```
## WTS
```
        workflow_input["enable_duplicate_marking"] = False
        workflow_input["enable_rna"] = True
        workflow_input["enable_rna_quantification"] = True
        workflow_input["enable_rrna_filter"] = True
```

### CODE REVIEW

**Comment by victorskl** [comment]
[Portal Release - Ocicat: Run WTS QC workflow through Portal before running Dragen WTS Tumor Only Workflow](https://trello.com/c/H0DQyo2B/1485-portal-release-ocicat-run-wts-qc-workflow-through-portal-before-running-dragen-wts-tumor-only-workflow)

**Review by victorskl — APPROVED** [review]
LGTM, Alexis!

**Comment by alexiswl** [comment]
Might hold this while we tinker with the rrna filtering, quant metrics etc that we might also need to add in to the wts qc configuration

**Comment by victorskl** [comment]
Okie, dokie..! Saw those discussion, yes. 
Or, can be another PRs; all good & leave it to you..!

**Comment by victorskl** [comment]
Related infra pull https://github.com/umccr/infrastructure/pull/334

**Review by victorskl — APPROVED** [review]

**Pull request merged**
