### PR TITLE
Added manops

### PR DESCRIPTION
**Pull request by victorskl**
* Hard set orchestration to bypass RNAsum step
* Introduce semi-automated manops
* Added rnasum doco for howto
* SLS deployed for new Lambdas

### CODE REVIEW

**Review by reisingerf — APPROVED** [review]
Awesome!

**Review by victorskl — COMMENTED** [review]
@skanwal @JMarzec The ICA Pipeline `manops` concept introduced in this PR and, please kindly review the `rnasum.md` doco which explain the "semi-automated" approach implemented i.e. RNAsum ops on ICA Pipeline. And still happy to discuss/amend the approach implemented, if any.

**Comment by skanwal** [comment]
Thanks @victorskl - added to my `to-do` for tomorrow.

**Comment by victorskl** [comment]
I guess, Sehrish and Jacek must be busy. That's ok. Since this is the first pass for RNAsum and, it is still manual driving. We can revisit and refine the process; if need be; with future iterations.

Merging this soon in tick, next.

**Comment by skanwal** [comment]
@victorskl - I had a read of this and made sense to me in terms of manual kick-off.
Are we using any one of these options?

**Comment by victorskl** [comment]
> Are we using any one of these options?

Yep; we will using either options -- mostly manops option -- to trigger RNAsum on ICA pipeline upon umccrise completion. Then, we shall have fully automated flow; probably in next few iterations.

> And sorry, slipped my mind to mention this to you before.

Ah no worries.

**Comment by victorskl** [comment]
Merging....

**Pull request merged**
