### PR TITLE
Release 2.2.3

### PR DESCRIPTION
**Pull request by scwatts**
- See [Release 2.2.3 milestone](https://github.com/umccr/data-portal-apis/milestone/21)

### CODE REVIEW

**Comment by victorskl** [comment]
Let me work on Portal documentation.

**Comment by scwatts** [comment]
Okay no rush from my side!

**Comment by victorskl** [comment]
Ocicat (Backport 3) Release Validation Documentation

https://docs.google.com/document/d/1xsWR1Z7kbPQTt-ZV0X8uoC4xhS4xE0Wy2BNZ7iB2G1A/edit

**Comment by victorskl** [comment]
Got the green light. Let ship it through prod.!

**Review by victorskl — APPROVED** [review]

**Pull request merged**
