### PR TITLE
Initialise RNAsum automation

### PR DESCRIPTION
**Pull request by skanwal**
## Files changed:
* config.py
  * Added RNAsum QUEUE ARN

* workflow.py
  * Added rnasum as a workflow type

* Orchestrator.py
  * Added an elif segment for handling the completion of umccrise ica workflow runs.
  * A potential change/discussion point: should we also check for WTS workflow notification here?

* liborca.py
  * Add in function for collecting the dragen transcriptome output directory
  * Add in function for collecting the umccrise output directory output directory

## Files created:
* rnasum.py
  * Handle event, update template for RNAsum workflow with input from event and then trigger workflow
  * For discussion: added `subject_identifier` to construct workflow run name and `library_identifier` to link workflow and library run. Check if this info can be accessed in another way.

* rnasum_step.py
  * Use inputs and outputs from transcriptome and umccrise run triggers to determine inputs for RNAsum workflow
  * For discussion: Since we need both transcriptome and umccrise output directories, `prepare_rnasum_jobs` function potentially will need to be passed both workflows as input?
  * TBD: Get patient specific reference dataset via REDCAP? line#72

### CODE REVIEW

**Comment by victorskl** [comment]
Thanks Sehrish. I will start work on it sometime next week.

**Review by victorskl — COMMENTED** [review]
Thanks Sehrish. So far so good, actually. Noted about discussion points and, will answer/work on those next. Let me take over the branch for that. After then, we shall regroup and cross check again.

**Comment by victorskl** [comment]
Rebasing the branch to on top of dev, FYI

**Comment by victorskl** [comment]
@skanwal @reisingerf Pls review the latest of this branch; (also answered Qs raised by Sehrish in code comments as solving them along) and, changes summary in commit comment https://github.com/umccr/data-portal-apis/commit/24a16da1e7eb7d6da8a212b47c4699000a14d605

I am working on unit testing, next. Happy to get feedback/Qs; if any.

**Review by reisingerf — APPROVED** [review]
LGTM
It just considering a subset of desirable RNAsum use cases, right?
(no objection, just observing)

**Review by victorskl — APPROVED** [review]
> It just considering a subset of desirable RNAsum use cases, right?

Thanks for checking, Flo. Yes, kind of. RNAsum comprises of slightly differing requirements and inter-workflow dependencies than others.

Happy to merge this now from my side at this point. @skanwal added you back as reviewer for waiting final approval tick. 

I am brew-ing "manops" concept (next) for howto semi-automated run in ICA Pipeline.

**Comment by victorskl** [comment]
Ah, GitHub does not allow PR submitter be a reviewer! Ok, pls comment, if any. Otherwise, I will merge it soon. Thanks.

**Comment by reisingerf** [comment]
Yup, happy to move ahead (approved already ;-) )

**Comment by victorskl** [comment]
Merging...

**Comment by skanwal** [comment]
Sorry about the delay @victorskl - I was planning to look at it today but guess that won't be needed. 
Happy to move this a long and continue discussion in the other PRs.

**Comment by victorskl** [comment]
Ah, sure, no worries. Let continue on in manops PR #418

**Pull request merged**
