### PR TITLE
Dracarys orchestrator

### PR DESCRIPTION
**Pull request by andrei-seleznev**
Initial dracarys orchestrator work - a dracarys_multiqc step to fire in orchestrator.py and fling multiqc jsons, if found, to the dracarys lambda (which ultimately places them inS3) see https://github.com/umccr/dracarys-to-s3-cdk

See integration tests for dracarys_multiqc_step for examples of how this works

### CODE REVIEW

**Review by victorskl — COMMENTED** [review]
Holding off this for 3 reasons.

- https://github.com/umccr/data-portal-analytics/tree/master/umccr_datalake
- https://umccr.slack.com/archives/C03PZS0N2JJ/p1666930447285049
- OrcaBus

Dear Andrei. Not your fault. I know we discussed this way initially and, you contributed this far. Thank you! However. We might / should better handle building this QC warehouse/datalake pipeline slightly differently. When you are able, please have a look to `umccr_datalake` notes from `data-portal-analytics` repo.

For now, I'm holding off merge; mainly to protect any side effect to main pipeline orchestration -- well, at least, during holis time window! 😉 

We shall revisit this tad a bit later; sometime next year milestone to re-align where it fit into. So, I put this PR in Draft mode for now.

cc @andrei-seleznev @pdiakumis @reisingerf @brainstorm

**Comment by brainstorm** [comment]
The Dockerfile included here has some building challenges under `arm64`, unfortunately... will try to simplify deployment/payloads and hopefully fix...

```
(...)
#9 [ 6/13] RUN /bin/bash /tmp/mambaforge.sh -b -p "/opt/mambaforge" && rm /tmp/mambaforge.sh
#9 sha256:207d7187ba5beccd997ffb2fc464bbe5fc6e31b6c003851631bcc6ef46290da8
#9 0.242 PREFIX=/opt/mambaforge
#9 0.561 Unpacking payload ...
#9 0.563 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
#9 0.567 /tmp/mambaforge.sh: line 366: /opt/mambaforge/preconda.tar.bz2: No such file or directory
#9 ERROR: executor failed running [/bin/sh -c /bin/bash /tmp/mambaforge.sh -b -p "${MAMBA_PREFIX}" && rm /tmp/mambaforge.sh]: exit code: 1
------
 > [ 6/13] RUN /bin/bash /tmp/mambaforge.sh -b -p "/opt/mambaforge" && rm /tmp/mambaforge.sh:
------
executor failed running [/bin/sh -c /bin/bash /tmp/mambaforge.sh -b -p "${MAMBA_PREFIX}" && rm /tmp/mambaforge.sh]: exit code: 1

 ❌ Building assets failed: Error: Building Assets Failed: Error: Failed to build one or more assets. See the error messages above for more information.
    at buildAllStackAssets (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:342:116743)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CdkToolkit.deploy (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:342:142824)
    at async exec4 (/opt/homebrew/lib/node_modules/aws-cdk/lib/index.js:397:51795)

Building Assets Failed: Error: Failed to build one or more assets. See the error messages above for more information.
```

**Comment by pdiakumis** [comment]
Thanks Roman. Is it imperative to build under `arm64`? From memory you need to add any missing conda packages to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt, which was not ideal going back ~12 months, that's why I build with `amd64`.

**Comment by brainstorm** [comment]
> Thanks Roman. Is it imperative to build under `arm64`? From memory you need to add any missing conda packages to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt, which was not ideal going back ~12 months, that's why I build with `amd64`.

Not imperative at all, just makes local dev a bit more cumbersome... I'll just spin up an Intel (amd64/x64) instance. As you point out, I suspect conda's `arm64` might still not be up to speed as of today anyway, so not going down that rabbit hole for now :-S

**Review by victorskl — COMMENTED** [review]
FYI. As discussed with Roman; I will rebase this branch on top of dev. Hence, will be force pushed.

**Comment by victorskl** [comment]
As discussed devops catchup 02/03/2023; descoping from `2.1`. And re-target it to `2.2` milestone that will align up with [Ocicat](https://github.com/umccr/infrastructure/milestone/10).

**Comment by brainstorm** [comment]
I reckon that #551 supersedes (and reuses!) this excellent work by @andrei-seleznev, thanks!

**Pull request closed without merging**
