### PR TITLE
Add CTTSO500 report ingestion

### PR DESCRIPTION
**Pull request by brainstorm**
Add the same basic infrastructure for S3 reports ingestion first as it's unclear (to me) which object-event methods are available for GDS at this point in the portal.

### CODE REVIEW

**Comment by alexiswl** [comment]
Just looking through this, does the `persist_report` function in https://github.com/umccr/data-portal-apis/blob/86c27b3800a07720f5c97c86296111cc5ccaebe5/data_processors/reports/lambdas/report_event.py currently support gds? Does it help knowing the files will be under `gds://production/analysis_data/<SUBJECT_ID>/dragen_tso_ctdna/`?

**Comment by brainstorm** [comment]
No it doesn't support GDS (yet) since I was going with S3 until I learned that the data would sit in GDS instead.

Will be that location fixed for the ctTSO500 reports? If so, yeah, it'd help a ton because we could just scan that prefix and be done, which is exactly what we needed to know before stalling on this draft PR :)

**Comment by alexiswl** [comment]
> If so, yeah, it'd help a ton because we could just scan that prefix and be done, which is exactly what we needed to know before stalling on this draft PR :)

Here are a few examples to go through on the dev side:

```
$ gds-find --gds-path gds://development/analysis_data/ --type directory --name 'dragen_tso_ctdna'
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00568/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00569/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00592/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00605/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00625/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00669/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00676/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00776/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00777/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00778/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00779/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00780/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00781/dragen_tso_ctdna/
gds://development/analysis_data/SBJ00782/dragen_tso_ctdna/
```

A closer look at the file listing:

```
$ gds-ls gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/  

$ gds-ls gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/dsdm.json
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/MetricsOutput.tsv
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/

$ gds-ls gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/evidence.PRJ200603_L2100345.bam
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/evidence.PRJ200603_L2100345.bam.bai
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.AlignCollapseFusionCaller_metrics.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.bam
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.bam.bai
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.bam.md5sum
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.cleaned.stitched.bam
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.cleaned.stitched.bam.bai
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.fragment_length_hist.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.msi.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.TargetRegionCoverage.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345.tmb.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_CopyNumberVariants.vcf.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_CopyNumberVariants.vcf.gz.tbi
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_Failed_Exon_coverage_QC.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_Failed_Exon_coverage_QC.txt
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_Fusions.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_MergedSmallVariants.genome.vcf.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_MergedSmallVariants.genome.vcf.gz.tbi
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_MergedSmallVariants.vcf.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_MergedSmallVariants.vcf.gz.tbi
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_MergedSmallVariantsAnnotated.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_MergedSmallVariantsAnnotated.json.gz.jsi
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_SampleAnalysisResults.json.gz
gds://development/analysis_data/SBJ00476/dragen_tso_ctdna/2021-08-26__05-39-57/Results/PRJ200603_L2100345/PRJ200603_L2100345_TMB_Trace.json.gz
```

**Comment by victorskl** [comment]
Hey Roman @brainstorm, pls have a look https://github.com/umccr/data-portal-apis/commit/9fd676cd9eedf62183f68c69a4ed93d175b1573f when you are able. It involves a bit more than I initially thought. But, anyway, this should do the trick! If you agree, I would merge it soon. Thanks.

**Comment by brainstorm** [comment]
Very nice Victor! I didn't anticipate that many changes either :-!!

Other than the couple of comments I just left, LGTM!

**Pull request merged**
