### PR TITLE
Deprecate Portal Report processing

### LINKED ISSUE #480: Deprecate Portal Report processing in favour of Dracarys pipeline
**Context:**

As solution noted by Roman[1], we shall migrate Portal Report processing be replaced with Dracarys[2] ETL/Datalake pipeline.

[1] https://github.com/umccr/data-portal-analytics/tree/master/aws
[2] https://github.com/umccr/dracarys

**Impact:**

- Currently there is no effective usage of this processed Report data from Portal

**Actions:**

- Deprecate [reports processor](https://github.com/umccr/data-portal-apis/tree/dev/data_processors/reports)
- Decommission [Report table](https://github.com/umccr/data-portal-apis/blob/dev/docs/model/data_portal_model.pdf)

### PR DESCRIPTION
**Pull request by victorskl**
* In favour of Dracarys pipeline

Fixed #480

### CODE REVIEW

**Comment by victorskl** [comment]
- [ ] #513 need to be merged first

**Comment by victorskl** [comment]
@pdiakumis FYI 🙂

**Review by williamputraintan — APPROVED** [review]

**Review by williamputraintan — COMMENTED** [review]
LGTM

**Review by reisingerf — APPROVED** [review]
LGTM

**Pull request merged**
