### PR TITLE
Refactor HTTP Query Params

### PR DESCRIPTION
**Pull request by williamputraintan**
- Created reusable function for the query params (fc8afe1). This modifies the query parameter to match with field names 
(The previous implementation may have a slightly different name to query the specific field name. For example, old implementation query `subject_id` with the keyword `subject`, where this PR change the query parameter to `subject_id`)
- Refactor viewsets and manager model to use the function. The following affected models:
  - Sequence
  - SequenceRun
  - Workflow
  - Metadata
  - Reports
  - LibraryRun
  - FastQ

~~_*Implementing on other models.manager might also need to change of current portal-client query parameter. This is because portal-client have a parameter of a subject that is searched on subject_id instead of having the same params as the field names._~~
_*Status page needs to change query parameter to align with this PR._

### CODE REVIEW

**Comment by victorskl** [comment]
Just want to say, I will take time going thought this. Probably will find sometime in next week.

**Comment by reisingerf** [comment]
Great! 
William and I had a quick chat about the `keyword` use case and the checking of allowed parameters.
@victorskl let us know when you start, so we can catch you up. 
@williamputraintan if you haven't started on the discussed changes, then it's probably better to wait for Victor's input.

**Review by victorskl — APPROVED** [review]
Ok folks! I made a bit of improvement. Please have a peek into this commit https://github.com/umccr/data-portal-apis/commit/9f196a3c7cee40c7281ecf36c895dadda8311f09 and, the comment there for summary changes.

Tests are passing. So, I am happy to merge this through very soon!

**Review by victorskl — COMMENTED** [review]
Thanks guys @williamputraintan @reisingerf catch up review call. As agreed, I am merging this now.

**Pull request merged**
