### PR TITLE
Fixed Supported ctTSO LabMetadata sample Type Assay combo

### LINKED ISSUE #508: Harmonise ctTSO LabMeta Type and Assay conditions check between workflows
**Context:**

* Especially, on TSO workflow; make sure we should probably throw an error upfront when we have type/assay combos that we do not recognise.

* Currently only support the following combo for our `tso_ctdna_tumor_only` workflow (or Portal internal enum `DRAGEN_TSO_CTDNA_STEP`)

```
type: ctDNA
assay: ctTSO
```

* See https://umccr.slack.com/archives/C025TLC7D/p1665367457696609

**Actions:**

* Make sure `bcl_convert` and `dragen_tso_ctdna_step` evaluate the same condition type and assay

### PR DESCRIPTION
**Pull request by victorskl**
Fixed #508

### CODE REVIEW

**Review by alexiswl — APPROVED** [review]
Great work!

**Comment by reisingerf** [comment]
This will exclude a specific type/assay combination, but the GH issue mentions to exclude all but the known/supported ones?

Why the "If UNSUPPORTED then fail" instead of "if not SUPPORTED then fail"?

Sorry, I may be missing some context here.

**Comment by victorskl** [comment]
Eh. El. Ok. Think, I got wut you mean. 

You mean other samples type and assay combo? I would not consider those yet. That would be pretty broad meta evaluation that might need done elsewhere... I think. May be, at SampleSheet Checker?

I think, I might write the GH issue description a bit vague. My aim is being specific and, fail-safe switch here. Such that this ctTSO annotation combo is well-known and, the most hotspot failure/confusion point. So want to eliminate that.

**Comment by reisingerf** [comment]
I know and I agree that this will eliminate this known issue case.

All I am saying is: are we keeping the door open for other cases where we could easily close it? 
Just saying that looking at the past, the issue was usually not in being too restrictive, but in being too permissive/inclusive. 

In this case here, I don't know. 
What's your opinion @alexiswl ?

**Review by reisingerf — APPROVED** [review]
For the current case it looks OK.
(don't what to stall over improvements)

**Review by victorskl — COMMENTED** [review]
(Ok, updated GH issue tickey to reflect specific to ctTSO case.)

Baby step, Flo! Baby step. 👶 We will get there, sure. 😉 And... towards OrcaBus! 🐳

**Comment by alexiswl** [comment]
> I know and I agree that this will eliminate this known issue case.
> 
> All I am saying is: are we keeping the door open for other cases where we could easily close it? Just saying that looking at the past, the issue was usually not in being too restrictive, but in being too permissive/inclusive.
> 
> In this case here, I don't know. What's your opinion @alexiswl ?

Yeah I think allowlist is probably a better way to control than a blocklist. But probably need to think about this further.

**Pull request merged**
