### PR TITLE
Improved Somalier Holmes pipeline integration

### PR DESCRIPTION
**Pull request by victorskl**
* Refactored integration into Somalier Holmes domain interfaces
* Refactored liborca bam output parsing explicit to workflow
* Added SOMALIER_EXTRACT_STEP to skippable step list
* Added sls deployment descriptor for Lambda and SQS event hook
* Improved unit test cases

### CODE REVIEW

**Comment by victorskl** [comment]
@andrewpatto @williamputraintan FYI & pls feel free to review, if you have time spare.

**Comment by victorskl** [comment]
Follow up / related #459

**Review by alexiswl — APPROVED** [review]
The separation of somalier and holmes seems to structure well here!

**Review by reisingerf — APPROVED** [review]
LGTM
I like the encapsulation of the holmes internals into a separate service, but it makes me wonder how much of that could/should be pushed back to holmes directly (exposing a stand alone service interface rather than raw pieces of infrastructure). Perhaps one for future consideration ;-)

**Review by victorskl — COMMENTED** [review]
Thanks folks for reviews. Gonna merge this in tick, soon.

**Pull request merged**
