### PR TITLE
Release 2.2.2

### PR DESCRIPTION
**Pull request by victorskl**
See https://github.com/umccr/data-portal-apis/milestone/20?closed=1

Ocicat (Backport 2) Release Validation Documentation
https://docs.google.com/document/d/1KZlO_VLieDc2nNPqkaH2UzY5lLV82I9eL_S64X3xEu0/edit

### CODE REVIEW

**Comment by victorskl** [comment]
CAB request is a go, ditto - https://umccr.slack.com/archives/CP356DDCH/p1721173590790749

**Comment by victorskl** [comment]
FYI @reisingerf

**Review by skanwal — APPROVED** [review]
Lets do this!

**Review by pdiakumis — APPROVED** [review]
Thank you

**Review by williamputraintan — APPROVED** [review]

**Comment by victorskl** [comment]
Runway clear. Taking off.!

**Pull request merged**
